[devops/ci] updating to latest rexpy so we can flter lines from tools…
New-Creta/Rex pull request #80
Opened 2023-04-19 01:04 UTC by RisingLiberty

… to only display errors

2023-04-23 19:46 UTC, Dyronix requested changes

2023-04-23 19:46 UTC, Dyronix commented on _test.py
> +  parser.add_argument("-filter_lines", help="filter lines to only display warnings and errors", action="store_true")
Kind of a weird name for this argument don't you think?
I had to read the description to see what it does.

2023-04-28 10:45 UTC, RisingLiberty commented
updated

2023-04-30 20:32 UTC, Dyronix approved these changes

2023-04-30 20:32 UTC, merged